apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ .Values.consumer.namespace }}
spec:
  type: ExternalName
  externalName: {{ include "postgres.fullname" . }}-{{ .Values.dbname }}.{{ .Values.namespace }}.svc.cluster.local
